/**
 * Verbatim, deterministic speech. These strings are never generated by the LLM:
 * legally mandated disclosures (FDCPA §1692e(11)), voicemail content
 * (no debt details — third parties may hear it), read-backs, and outcome
 * confirmations derived from the committed record.
 */
import type { PublicContext } from "./context.js";
import type { IsoDate, IsoDateTime, MoneyAmount } from "./values.js";

export const miniMiranda = (ctx: Pick<PublicContext, "agent_name" | "company">): string =>
  `This is ${ctx.agent_name} calling from ${ctx.company}. This is an attempt to collect a debt, and any information obtained will be used for that purpose.`;

export const recordingDisclosure = (): string => "This call may be recorded for quality and training purposes.";

export const openingQuestion = (ctx: Pick<PublicContext, "borrower_first_name">): string =>
  `May I please speak with ${ctx.borrower_first_name}?`;

/** The full non-interruptible opening: disclosures + right-party question. */
export const openingScript = (ctx: PublicContext): string =>
  `${miniMiranda(ctx)} ${recordingDisclosure()} ${openingQuestion(ctx)}`;

/** FDCPA-safe voicemail: name, company, callback number. No debt details. */
export const voicemailScript = (ctx: Pick<PublicContext, "agent_name" | "company" | "callback_number">): string =>
  `Hello, this is ${ctx.agent_name} from ${ctx.company}. Please return our call at ${ctx.callback_number} at your earliest convenience. Thank you.`;

export const spokenIsoDate = (iso: IsoDate | string): string => spokenDate(iso);
export const spokenMoney = (amount: MoneyAmount | string): string => spokenAmount(amount);

const spokenDate = (iso: IsoDate | string): string => {
  const [y, m, d] = String(iso).split("-").map(Number);
  const dt = new Date(Date.UTC(y ?? 1970, (m ?? 1) - 1, d ?? 1));
  return dt.toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric", year: "numeric", timeZone: "UTC" });
};

const spokenAmount = (amount: MoneyAmount | string): string => {
  const [whole, frac = "00"] = String(amount).split(".");
  const dollars = Number(whole).toLocaleString("en-US");
  return frac === "00" ? `${dollars} dollars` : `${dollars} dollars and ${Number(frac)} cents`;
};

/**
 * Why a `record_promise_to_pay` was refused. All three are `TOOL_REJECTED` / `INVALID_ARGS`, and
 * they mean different things: the first two are the fully-heard guard doing its job on a real
 * proposal, the third is the model inventing a record with nothing to record. They live here, next
 * to the read-back they are about, because the reliability counter keys off the difference —
 * matching a prose string written somewhere else is exactly how a counter starts lying.
 *
 * The guard distinguishes a read-back the borrower demonstrably did not hear all of from one
 * nobody can say anything about, because they are diagnosed differently: the first is a barge-in
 * (normal, and the repeat is the product working), the second is a worker that died after
 * speaking, a signal POST that failed or a job process that went away (a fault, and the repeat is
 * damage control). Both count into `readbacks_repeated_unheard`.
 */
export const READBACK_INTERRUPTED_DETAIL = "read-back was interrupted; repeating it";
export const READBACK_UNCONFIRMED_DETAIL = "no playout confirmed the read-back was heard; repeating it";
export const NO_PENDING_PROPOSAL_DETAIL = "no pending proposal to record";

/** The two details the fully-heard guard rejects with — the reliability counter's filter. */
export const READBACK_UNHEARD_DETAILS = [READBACK_INTERRUPTED_DETAIL, READBACK_UNCONFIRMED_DETAIL] as const;

/** Read-back for a proposed promise to pay (non-interruptible). */
export const promiseReadback = (p: { readonly amount: MoneyAmount | string; readonly date: IsoDate | string }): string =>
  `To confirm: you will pay ${spokenAmount(p.amount)} by ${spokenDate(p.date)}. Is that correct? Please say yes to confirm.`;

/** Confirmation spoken only after the promise is durably recorded. */
export const promiseRecordedConfirmation = (p: {
  readonly amount: MoneyAmount | string;
  readonly date: IsoDate | string;
}): string =>
  `Thank you. I have recorded your promise to pay ${spokenAmount(p.amount)} by ${spokenDate(p.date)}. Goodbye.`;

const spokenDateTime = (iso: IsoDateTime | string, timeZone: string): string =>
  new Date(String(iso)).toLocaleString("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
    timeZone,
    timeZoneName: "short",
  });

/** Confirmation spoken only after the callback is durably scheduled. */
export const callbackScheduledConfirmation = (p: { readonly datetime: IsoDateTime | string; readonly timeZone: string }): string =>
  `Understood. I have scheduled a callback for ${spokenDateTime(p.datetime, p.timeZone)}. Goodbye.`;

export const optOutConfirmation = (): string => "Understood. We will stop contacting you. Goodbye.";
export const wrongNumberClose = (): string =>
  "Thank you for letting us know. We will update our records and will not call this number again. Goodbye.";
export const thirdPartyClose = (): string =>
  "Understood. I will not discuss the matter further. We will try again another time. Thank you, goodbye.";
export const disputeClose = (): string =>
  "I understand that you are disputing this debt. I will stop here and have a specialist follow up with you. Goodbye.";
export const hardshipClose = (): string =>
  "I understand, and I'm sorry to hear that. I will stop the payment discussion and have a specialist follow up with you. Goodbye.";
export const holdForTransfer = (): string => "Please hold while I connect you to a specialist.";

export const noInputPrompt = (strike: number): string =>
  strike >= 2 ? "I am not hearing a response, so I will end this call and try again later. Goodbye." : "Are you still there?";

/** Safe fallback when the decider fails or produces an unusable turn. State-neutral. */
export const safeFallback = (): string => "I'm sorry, could you say that again?";

export const genericGoodbye = (): string => "Thank you for your time. Goodbye.";
