from enum import StrEnum


class BorrowerStatus(StrEnum):
    ACTIVE = "ACTIVE"
    OPT_OUT = "OPT_OUT"
    DECEASED = "DECEASED"


class ContactPointType(StrEnum):
    PHONE = "PHONE"


class ConsentStatus(StrEnum):
    ALLOWED = "ALLOWED"
    OPTED_OUT = "OPTED_OUT"
    UNKNOWN = "UNKNOWN"


class ContactRelationship(StrEnum):
    PRIMARY = "PRIMARY"
    CO_BORROWER = "CO_BORROWER"
    OTHER = "OTHER"


class LoanStatus(StrEnum):
    CURRENT = "CURRENT"
    DELINQUENT = "DELINQUENT"


class AgentVersionStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    RETIRED = "RETIRED"


class WorkflowType(StrEnum):
    PAYMENT_REMINDER = "PAYMENT_REMINDER"
    CALLBACK_FOLLOWUP = "CALLBACK_FOLLOWUP"
    ESCALATION_FOLLOWUP = "ESCALATION_FOLLOWUP"


class WorkflowExecutionStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class CallDirection(StrEnum):
    OUTBOUND = "OUTBOUND"
    INBOUND = "INBOUND"


class CallAttemptStatus(StrEnum):
    INITIATED = "INITIATED"
    ANSWERED = "ANSWERED"
    NO_ANSWER = "NO_ANSWER"
    VOICEMAIL = "VOICEMAIL"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class ConversationState(StrEnum):
    GREETING = "GREETING"
    VERIFYING_IDENTITY = "VERIFYING_IDENTITY"
    DISCUSSING_PAYMENT = "DISCUSSING_PAYMENT"
    CONFIRMING_OUTCOME = "CONFIRMING_OUTCOME"
    VOICEMAIL = "VOICEMAIL"
    THIRD_PARTY_OR_WRONG_PARTY = "THIRD_PARTY_OR_WRONG_PARTY"
    WARM_TRANSFER_PENDING = "WARM_TRANSFER_PENDING"
    OPT_OUT = "OPT_OUT"
    WRONG_NUMBER = "WRONG_NUMBER"
    ESCALATED = "ESCALATED"
    ENDING = "ENDING"
    COMPLETED = "COMPLETED"


class Outcome(StrEnum):
    PROMISE_TO_PAY = "PROMISE_TO_PAY"
    CALLBACK_SCHEDULED = "CALLBACK_SCHEDULED"
    WRONG_NUMBER = "WRONG_NUMBER"
    OPT_OUT = "OPT_OUT"
    ESCALATED = "ESCALATED"
    DISPUTED = "DISPUTED"
    VOICEMAIL_LEFT = "VOICEMAIL_LEFT"
    THIRD_PARTY_CONTACT = "THIRD_PARTY_CONTACT"
    NO_ANSWER = "NO_ANSWER"
    FAILED = "FAILED"


class EventType(StrEnum):
    CALL_STARTED = "CALL_STARTED"
    CALL_CONTROL = "CALL_CONTROL"
    AMD_RESULT = "AMD_RESULT"
    NO_INPUT = "NO_INPUT"
    USER_TURN = "USER_TURN"
    USER_TURN_FINAL = "USER_TURN_FINAL"
    AGENT_TURN = "AGENT_TURN"
    TOOL_CALLED = "TOOL_CALLED"
    TOOL_RESULT = "TOOL_RESULT"
    STATE_TRANSITION = "STATE_TRANSITION"
    TRANSFER_REQUESTED = "TRANSFER_REQUESTED"
    TRANSFER_COMPLETED = "TRANSFER_COMPLETED"
    CALL_ENDED = "CALL_ENDED"
    OUTBOX_ENQUEUED = "OUTBOX_ENQUEUED"
    OUTBOX_PROCESSED = "OUTBOX_PROCESSED"


class ScheduledActionType(StrEnum):
    CALLBACK = "CALLBACK"
    RETRY_CALL = "RETRY_CALL"
    HUMAN_FOLLOWUP = "HUMAN_FOLLOWUP"


class ScheduledActionStatus(StrEnum):
    PENDING = "PENDING"
    CLAIMED = "CLAIMED"
    DONE = "DONE"
    CANCELED = "CANCELED"


class OutboxJobType(StrEnum):
    SUMMARY = "SUMMARY"
    EVALUATION = "EVALUATION"
    VECTOR_INDEX = "VECTOR_INDEX"


class OutboxJobStatus(StrEnum):
    PENDING = "PENDING"
    CLAIMED = "CLAIMED"
    DONE = "DONE"
    FAILED = "FAILED"
